### ISSUE TITLE
Get Content by tag

### ISSUE THREAD

**Issue by khraibani** [JasonEspin/jezzipin.TagliatelleTagManager#3]
Hello, great package! It would be great for some documentation on how to get a list of IPublishedContent from a document type /tags/tag-name/

**Comment by JasonEspin** [comment]
If you look on Our Umbraco there should be a guide on there as I have now
added a property value converter to the package

**Comment by khraibani** [comment]
Thanks for the swift reply, can you please point to me to the right url?

**Comment by JasonEspin** [comment]
No problem. Looks like I haven't put it up there yet. Been very busy.
Basically if you use something along the lines of:

page.GetPropertyValue<IEnumerable<IPublishedContent>>("propertyname")

This will give you a list of IPublishedContent elements for each of the
pages you have selected.

**Comment by khraibani** [comment]
Sorry that didn't work.
What I basically want is when the user go to the following url: mywebsite.com/tags/mixed-media/
a list of all pages that has been tagged with mixed-media.

Thanks for your help much appreciate it.

**Comment by JasonEspin** [comment]
That's not what this tool is for unfortunately. It's fairly easy to do
though using my tool. Have a look on the official Umbraco forums and that
should give you an idea as to how. For now I'll close this issue as there
isn't really a problem with my plugin.

**Comment by khraibani** [comment]
No problem thanks for help anyway.

**Comment by JasonEspin** [comment]
If it helps, the tag manager stores the IDs of each page as the page of so
all you would need to do is get all of the defendants of the homepage that
have a property containing the ID of the current page. Should be really
easy using Linq

**Comment by codebreach** [comment]
it would be useful to have this documented

**Comment by JasonEspin** [comment]
It is already documented in the Umbraco Core. Take a look at Standard
Property converters. This works in the same way.

**Comment by codebreach** [comment]
Woah thanks for the quick reply!
I just used this (like Standard Property converters)

```cs
var articles = Umbraco.TypedContentAtRoot().DescendantsOrSelf<Article>().Where(
       article => article.SectionTags.Select(tag => tag.Id).Contains(Model.Content.Id));
```
`Article` -> Document Type with tags
`SectionTags` -> Name of tags property

putting this here for the lazy :)
